apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-cluster1
  namespace: tools
spec:
  destination:
    namespace: default
    server: 'https://api.cluster1.ncolon.xyz:6443'
  source:
    path: guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      selfHeal: true

