apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello
spec:
  host: hello.apps.refarch.ncolon.xyz
  port:
    targetPort: 8080
  # tls:
  #   insecureEdgeTerminationPolicy: Redirect
  #   termination: edge
  to:
    kind: Service
    name: hello-kubernetes
    weight: 100
  wildcardPolicy: None
